# Generated by Django 3.1.6 on 2021-02-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='mobile',
            field=models.PositiveIntegerField(default=int),
            preserve_default=False,
        ),
    ]
