# Generated by Django 3.1.6 on 2021-02-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_register_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='register',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
