# Generated by Django 3.1.6 on 2021-02-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.ImageField(default=1, upload_to='pro/'),
            preserve_default=False,
        ),
    ]
