# Generated by Django 2.2 on 2022-04-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0007_register_exercise'),
    ]

    operations = [
        migrations.CreateModel(
            name='BmiMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_in_meters', models.FloatField(blank=True, null=True)),
                ('weight_in_kg', models.FloatField(blank=True, null=True)),
                ('measured_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AlterField(
            model_name='register',
            name='Exercise',
            field=models.CharField(choices=[('None', 'None'), ('Muscle Gaining', 'Muscle Gaining'), ('Cardio Fitness', 'Cardio Fitness'), ('Pilates', 'Pilates'), ('Yoga', 'Yoga'), ('Barre', 'Barre'), ('Crossfit', 'Crossfit')], default='None', max_length=50),
        ),
    ]
