# Generated by Django 2.2 on 2022-04-03 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0009_bmimeasurement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bmimeasurement',
            name='user',
        ),
    ]
