# Generated by Django 3.0 on 2022-04-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0010_remove_bmimeasurement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='forgot_ans',
            field=models.CharField(default='', max_length=100, verbose_name='Write Something Which Help You To Change Your Password'),
        ),
    ]
